### ISSUE TITLE
[Discussion] Custom Cursor

### ISSUE THREAD

**Issue by ghost** [suika2engine/suika2#110]
The ability to specify an image file to replace the default system cursor.
This could be toggle-able from the menubar/config screen.

See [[Discussion] Menubar Additions](https://github.com/suika2engine/suika2/issues/107)
See [[Discussion] v2.11.8 goals and schedule](https://github.com/suika2engine/suika2/issues/103) for full list.

**Comment by ktabata** [comment]
This is feasible but I would like to know how much demand there is. I look forward to many comments.

**Comment by innocentvoice** [comment]
I would also like to see suika2 support custom cursor too!

**Comment by Max-Morgan** [comment]
Idea of a custom cursor is always interesting! Because despite this small detail, we always see it, and some developers change it to suit the style of their games

Idea of a custom cursor is always interesting! Because despite this small detail, we always see it, and some developers change it to suit the style of their games

I have some idea in my head how it would be implemented:

```
mouse.idle=***.png
mouse.hover=***.png
mouse.block=***.png #When the button is not available
```

And:

```
START {
    type: goto;

    label: START;

    mouse: hover; #The name of texture that will appear when you hover

    x: 2;
    y: 495;
    width: 314;
    height: 192;
}
```
In script:
`@cursor ***.png`

+My idea was to add system cursor from your pc, but because of cross-platform issues idea came into question, If it is now possible, I would like to ask about it again

P.S. In addition, it would be interesting to make a watermelon cursor :)

**Comment by RaZZlom** [comment]
This is good idea.

In my opinion we need only 4 lines in `config.txt`:

```
cursor.idle=***.png
cursor.hover=***.png
cursor.block=***.png
```
like @Max-Morgan said, and `custom-cursor=true` that can be toggled `true` or `false` from in-game settings.

**Comment by KyouBrayden** [comment]
It would be beneficial to allow developers to toggle this from `config.txt`, although I feel that this goes without saying.
It would also be beneficial to allow developers to add only specific custom cursors.

For example:
```
cursor.idle=
cursor.hover=cr_hover.png
...
```
Where `cursor.idle` remains the system-default. Thanks for the input @Max-Morgan and @RaZZlom.
