### ISSUE TITLE
[Improvement] Web site and documentation.

### ISSUE THREAD

**Issue by RaZZlom** [suika2engine/suika2#133]
Now information about suika2 is scattered in many places:

https://github.com/suika2engine/suika2/tree/master/doc
https://github.com/suika2engine/suika2/wiki
http://suika2.com/
https://docs.suika2.com/
https://blog.suika2.com/

I propose to combine all the information in one place and provide links to all the web services.

How I see it:

https://suika2.com - a landing page with a short description of suika2 and the main features of the engine. On the same page, there should be links to https://github.com/suika2engine/suika2, https://docs.suika2.com and https://blog.suika2.com in the menu.

The old site, which is now at https://suika2.com/ does not need to be deleted, just moved to another domain, for example https://old.suika2.com/ .

https://docs.suika2.com - does not currently live up to its name. Move the content to suika2.com, and have the information currently in https://github.com/suika2engine/suika2/wiki at https://docs.suika2.com. Use a documentation generator, such as https://www.mkdocs.org/ or https://www.sphinx-doc.org/en/master/

https://blog.suika2.com - everything is fine here.

The information from https://github.com/suika2engine/suika2/tree/master/doc and https://github.com/suika2engine/suika2/wiki should be removed or you should learn to automatically sync with https://docs.suika2.com.

For all three of the above services, I think it is important to use the same or similar theme and to be able to translate the content into different languages.

**Comment by KyouBrayden** [comment]
There is a reason for the scattered way of doing things.

Because Suika2 is a multi-language community, the resources are spread between different oversight.

As far as I'm aware (and from discussions had with ktabata), Japanese prefer completely localised content.

https://suika2.com is where a majority of the Japanese information can be found (there is also a Chinese version there, although not as up-to-date, I think.)
https://suika2.com/en/ is no longer in use, and directs uses to https://docs.suika2.com.
https://docs.suika2.com is where English information is provided.
https://blog.suika2.com is where the blog is located, you can forget about this as it will be linked on docs.suika2.com soon.

Regarding 'https://docs.suika2.com - does not currently live up to its name':

I am building this. The reason that it isn't a copy+paste / generated documentation is because it needs to feature and follow specific regulations and naming conventions regarding accessibility. This is difficult with multi-user edited Wikis, therefore the website wiki will be built and maintained OUTSIDE of the GitHub Wiki by me. This is not a law or something I've been told to do – it is MY desired design doctrine to provide a clean and consistent experience outside of GitHub. Not just for accessibility, but language as well.

**Comment by KyouBrayden** [comment]
@RaZZlom I will close this issue for now, but I promise I am actively migrating and working on a lot of what you've mentioned above! I will make an announcement myself when things are sorted out on the English side! – I apologise.
